version: "3.8"

services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "-js --http_port 8222"
    volumes:
      - ./data/nats:/var/lib/nats
    environment:
      - NATS_DISABLE_SERVER_CHECK=true
    healthcheck:
      test: ["CMD", "nats", "server", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
